template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: packer
  name: packer
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: hashicorp/packer
    name: packer
    '''

properties([
    parameters([
        choice(choices: ['us-east-1', 'us-east-2', 'us-west-1', 'us-west-2'], description: 'Pick the region', name: 'region')
        ])
        ])

if (params.region == "us-east-1") {
    kaizen = "us-east-1"
}
else if (params.region == "us-east-2") {
    kaizen = "us-east-2"
}
else if (params.region == "us-west-1") {
    kaizen = "us-west-1"
}
else {
    kaizen = "us-west-2"
}


def buildNumber = env.BUILD_NUMBER


podTemplate(cloud: 'kubernetes', label: 'packer', showRawYaml: false, yaml: template){
node("packer"){
container("packer"){

stage ("Checkout SCM") {
    git branch: 'main', url: 'https://github.com/rano87/jenkins-july.git'
    
}

withCredentials([usernamePassword(credentialsId: 'aws-cred', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
withEnv(["AWS_REGION=${kaizen}"]) {

stage("Packer"){
  sh """
  cd packer
  packer init .
  packer build  -var 'jenkins_build_number=${buildNumber}' packer.pkr.hcl
  """
}
}
}
}
}
}








